spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/repertapp
        username: repertapp
        password: teste_repertapp
    jpa:
        # database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        # show-sql: true
        hibernate:
            ddl-auto: update # create-drop / update
        
        # properties:
        #     hibernate:
        #         # dialect: org.hibernate.dialect.postgreSQLDialect
        #         # "[format_sql]": true

    jackson:
        date-format: yyyy-MM-dd
        deserialization:
            fail-on-unknown-properties: true
        mapper:
            DEFAULT_VIEW_INCLUSION: true

server:
    port: 8080
    error:
        include-stacktrace: always # on-param #?trace=true

logging:
    level:
        org:
            springframework: ERROR
            hibernate:
                SQL: DEBUG
                # type: trace